Update .travis.yml
Fix Travis CI errors by raising the Ruby version from 2.2.2 to 2.3.0.

$ gem install html-proofer
Fetching: mercenary-0.3.6.gem (100%)
Successfully installed mercenary-0.3.6
Fetching: mini_portile2-2.4.0.gem (100%)
Successfully installed mini_portile2-2.4.0
Fetching: nokogiri-1.10.4.gem (100%)
ERROR:  Error installing html-proofer:
	The last version of nokogiri (~> 1.9) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1` and then running the current command again
	nokogiri requires Ruby version >= 2.3.0. The current ruby version is 2.2.0.
The command "gem install html-proofer" failed and exited with 1 during .